import assert from 'assert';

try {

} catch (error) {
  console.log(error)
}
